# Generated by Django 5.2.12 on 2026-03-14 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='שם')),
                ('email', models.EmailField(max_length=254, verbose_name='אימייל')),
                ('message', models.TextField(verbose_name='הודעה')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'הודעת יצירת קשר',
                'verbose_name_plural': 'הודעות יצירת קשר',
            },
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='שם ההופעה')),
                ('venue', models.CharField(max_length=200, verbose_name='מקום')),
                ('date', models.DateField(verbose_name='תאריך')),
                ('description', models.TextField(blank=True, verbose_name='תיאור')),
                ('ticket_url', models.URLField(blank=True, verbose_name='קישור לכרטיסים')),
            ],
            options={
                'verbose_name': 'הופעה',
                'verbose_name_plural': 'הופעות',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='שם היצירה')),
                ('description', models.TextField(blank=True, verbose_name='תיאור')),
                ('year', models.IntegerField(verbose_name='שנה')),
                ('audio_url', models.URLField(blank=True, verbose_name='קישור לאודיו')),
                ('cover_image', models.FileField(blank=True, upload_to='tracks/', verbose_name='תמונת כריכה')),
            ],
            options={
                'verbose_name': 'יצירה',
                'verbose_name_plural': 'יצירות',
                'ordering': ['-year'],
            },
        ),
    ]
