# Generated by Django 5.2.12 on 2026-03-14 08:59

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='audio_url',
        ),
        migrations.RemoveField(
            model_name='track',
            name='cover_image',
        ),
        migrations.AddField(
            model_name='track',
            name='audio_file',
            field=models.FileField(blank=True, upload_to='audio/', validators=[main.models.validate_audio], verbose_name='קובץ אודיו (MP3/WAV)'),
        ),
        migrations.AlterField(
            model_name='track',
            name='title',
            field=models.CharField(max_length=200, verbose_name='שם השיר'),
        ),
    ]
